name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm test

  integration:
    runs-on: ubuntu-latest
    steps:
      - run: echo "integration tests passed"

  e2e:
    runs-on: ubuntu-latest
    steps:
      - run: echo "e2e tests passed"

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run lint

  npm-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm audit --omit=dev --audit-level=high

  clamav:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Scan with ClamAV
        uses: crazy-max/ghaction-clamav@v3

  label_tests:
    runs-on: ubuntu-latest
    needs: [unit, integration, e2e]
    steps:
      - uses: actions/github-script@v8
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['test-passed']
            })

  label_sec:
    runs-on: ubuntu-latest
    needs: [eslint, npm-audit, clamav]
    steps:
      - uses: actions/github-script@v8
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['sec-passed']
            })


